# Generated by Django 3.0.8 on 2020-07-09 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingadress',
            name='country',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shippingadress',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
